from pathlib import Path
import base64, gzip

ROOT = Path('buildsrc/quiet-diary')


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'expected block not found in {path}: {old[:90]!r}')
    path.write_text(text.replace(old, new, 1), encoding='utf-8')


def write_gz64(rel: str, payload: str) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(gzip.decompress(base64.b64decode(payload)))

FILES = {
'app/src/main/res/layout/activity_night_assistant.xml': 'H4sIAOdph2oC/9VaW2/URhR+51dY28cqe8kmEFDCJSkVSKRUbNS+IK1m7cnuKLbHHc/mwhOQVrSCQqGoVBRoq1bqA60UpaSEbC4Sv2D8F/pLembsTez17I3djWikEM3MmfH4fOd852Kmz606trGMmU+oO5MpZPMZA7smtYhbncnU+eLYVObc2RPTV4iLEbuC1midG7DF9c8g12KUWDOZGufemVzON2vYQX42ms+a1MkhbynHsJ+L5jLNrZ7Xy7YxVOc0Y0QrZ2z19PIKsXhtJuMgbtbKHmLY5SmZGibVGm8nVEHmUpXRuguXP28xtIIqNs45iLjlo6UjccoIbEdcaQhUxYmJ7AwopWQyatufEbwy/DsukvBkjzKQ4ayOYxeCS4TPnqcWnsm4GCYyrSgNcKUVhryySV2eENLr4XDZQ5a0mhJH8sbjectLrS1QwL0wpVm5KLHQ7pmlnFMHFuW2sycM+Bnxe1YZWiZ8bSZjwjRm5fSrJjRRg9ENOEPZhBH9TF92UBV3MI3C+Hj8ZVsuVkzoKLrhR9g3GfHCp5ao48KDj4R8uCFeWPPAHhYJVyjEFpkZN3U/3FxeocxyEFvK5GI3L3nIxG1une9w54JmbaW5lngCuHi2SmnVxodeD3BhRpCdrdQBbjc7H41n1fDwWEk35z8kVs6V517wfeJz5PJL1MGhZMbw+ZoNOjiHOGc5J3HM1Tq3wXKskhRpxyt6m+jJcBzifq7RE0xfivZNJEDneBXmxHOxYYi/RUNsiE2xF6wH95MiF2x7Dnk+4IpsHyfX5qhNGejElH9zX1hl6paVbspOnWMrKVwiN0AzhYIv7+B5YFfMxewaskgdTi9MWtG8zxldwqmjK2At4A4VJs9vAjqdizvj2RPh5McMOXhw/yxM6JwELLZK3JBLJuLrel5vGjtqWkvZRMyKM33MNIfFLHqhPpmlLccqtiwUjhjx8P4LAHMH1hnAuG3M4cqSHFRqkM8WxlstuXR1/pOr1y4bb18bYNQvxB/izy7W6jECaK7pzPS03+IppdCxK9S24mzSy2sPEAzSNndK68L7wR2xJ/bFm+uuOIC/uzDzDcxsi50ePVanhPHJ91ULkxotfA/v3YD3viXfP2uIh2JLvDaCb8VOcBPIbU9sZAdnr3HQSDyYtPBPOBfjnyYljTZneDdq8hh2SN2Bs5Fi1j6Sz6Ez1uhyIb1ttgnls8iqjiI26wEIjc2sEU+r/EU45WPkEBsU4CPXH/Mhm1gcczBETKcDNeanYtEfrUqIZIBNOcwP4rH4zRBPgSufie+ARWA4AFucTrrG8WRzfaE7T0zITHndPzaE22LbCZdn4kcA5ReA5Xf4fa4C2iPxEuZ+GpjAeo1rOmLrqbKY6lRYaBdbnTzmxZ0I7mR3gqOsolW+rqIRv8rQEdyGfx+owLllQBTdVsFjP/gSYgoEkFQqBDGyGL9HS6VDzLJDAZRlSsx46kxcrvWqOAC9GrW0aLxAePuaYriBJQFhjxTVAnHsfDCyiLkurnKGQJ+J2uXQS4oaL0mAI2uYfQmf2Bwk4znVEt/7QaE9rwwVgURx3odmi3rNTmriwqtg3RA7Ko+UiRMMB8+ciu+o2TnwXW7RFfd/aN6hQie6KI8TB+tUVpyIk/Uy8UmF2Oo5VerihDI/ZbTKsO/PItZNn03RWK8i2qB6Ft7RSSo0XGrPxv3of6JzJZ2waeJaGNToEBeYLdV3AMsFo83n8zEyju4MOUV6cvYwACwo2v2gWJyYOzk5dSEtutDCy6n6sCMG2lS4DQjXsEmZDCBzoFpG7eNhjmTM7FLsp961JekaehuthJYP22hDV0asCzap64LJ6P9VVCduB7eDe4Z4DYMDGNwK7g3QEYtsqGzJRqfqb1VaDFJnb+n2mPSQ3KghmEOuie1h9TJHF/W6ofkCEoFdKP+HjGUsc9AD1Kl/2RIiuzYRdI3N97mL4KsM6N26CCNsHaX6hiljide/L0ffMewj8XEcEDmm0FDojnTUrgivpQU6nXSe1HxTa7WrCIcnRz4qS963LwGPPXDizbCPmXDit43rruRsyPt1oqoHuKeEHgGpb4nd4EEk+DSsEoKbwV3xxgjuiI3glhJ8GKyLV7C7EdyLTgk3pOaV9BP1uWQLjvk64phQWrViYRSWkuLgbWOAaiTVbTzOFmsyE+5STkQQ/qzarw1ZO8erh7sGaHBf/CP1CGrZUhCD4DbUbFBVy29PsfJNNrKV+razhvir2b2V1bg8AhYNsQng7QAi9wG/UPv/3nxsRB8lDXEgy0L1yAbsAAH5sEawDlhtSOnscL5idfwGNfz0iFPvvYzMhb5C86MUdArv6POFobwVMBO7A8RpC7lVVYb1H6WjrQBtK6zTuaP/cJFe/Q88f/G8yiIAAA==',
'app/src/main/res/layout/activity_practice_hub.xml': 'H4sIAOdph2oC/+1bW28TRxR+51es9rVgx44JSRQDgraiUgIIo/JSaTXendij7K2za0J4yqXQVqEKRUWiqE0JL7xUagJJY3JD6i+Y/Qv8kp6ZXcfr9Xrt2I7lSMmDvXvmzO7st+d85zLO1LVHhi49xNQhlpmXM6kRWcKmamnELOXlijt7aVy+dvXC1DQxMaLTaMGquBJMMZ1JZGrUIlpeLruuPZlOO2oZG8hJBfKUahlpZM+lKXbSgUyuTbXtTqZdQhXXkqVgZFIXd1fmieaW87KBXLWs2Ihi023SKWNSKrutlIpInStRq2LC4q9rFM2joo7TBiKmUh+qq1uUwHTkCoQAKpeoSJcBlIJKLV3/luD5XtY4otnNzxiMZeojs8S/lW1RGHBpBYdWCKvyFzNjaTgvmxgEcvS19bDGeYpsRbVMt0EpHpjjYRtp3IwKLuIrzoyHnzMYu2+BIWTGYka+4i8nds4Ny3UtIy+PcuCuXpDg75Sfs0TRQ+Iu5GUVxJgqzY/agEQZzh7DNYSRSMFfJ0uMs4TklbU2l1ZGK4X+pu7jR26C+Sbes83CsAtIFWykCiIZSWVy9UEXbpuXC3dmbt+59430367E/mJv2HP2mr1lr+DzVaPqTUu3KHiqyr/T32uKTYmB6EKjVoE8BsufcOyI2F3QQV60dE1On+zxe7CYQAlWWSKmMPLLmh0FAJ50k+1J7D07Yh+9ZVaFQ8n7xVv2ViR2yI68H71n19pAwYVxOGTPFBB/eCts11tle2zzouT94C0CMLv8mH0Sx3scHT4qwdc+B+oDwLMMuL2HWR8lb8l7ynYAs01Qr4Lg8+JvkhjbYjtcBLo7Eqhvc1wl+NoBxJdA+h7Ud1JtQDYqLtbiUM6MAsohMKfSYS8PySGopUqWVdLxcZwDUDElSE8VK8BnZmomOL8hTo9vxgPs9S+IlrYpUsGJcQE8C3zK8fVaRcdc7sRcYhDzVqDQODvQ/BI7KiW2zyjsT8AaAARwwXjh1VTr+sR0sDuNZ6OxTcjvxQQ9uPODGAb0jQPObXuSqPyu9WBNVMUJgKgr3PUDRO0ygTRwCC4LXlX0NfnCrykycISfm9C/zZd/l1oQEoybiGo9ZSeZibGYtxTylcb4F5+22BQbpGLARZEGsSkugVF1os5x5WjeMGupFSc0ELLYbwxUwgmckMmOJ1hY4uMfh1McXiTS7TLikWIi2fLqow5ENHx/wca1wHyTWqElOVQN4+RYhglBUam9ScWBSbjBe/uVRcQrnTCLaJlP+ZmRMI2BhfN40zP5FEUtEzvW7GrkztbZPxIQxjp7x/5uQ7WWqYirnqnYnhmNiWkbQIxbPHoBST77zoyGqB5wyF4eViCuJMd26fPTF6HwLk79RId/8ji+CBD9C/AcdAhPQmjONobmwRtFNgaMcNSscsM4TvQkjkb3eW8m16FNxKUoU+lQ7KuFw9Mtqdrh1W1B1RSwZyoOUZMidVLRlbmS7aw4b3gcQdBjnUdup2zNq8jBSlEPB+eOo/bJar52gX00KXNsHIx/LIsWY8OBXcvOGhKHSJSGvM7gbyxky8R0GyoeYuDhc+wQy3VbsY0MmtVHurBtgcBYDABveVjjNVeN3nisOwREoO46gJN9UX1Vuc422/fWoGZjn0C2J+oHTv8feGW2KwhyFYY2QVj11rqvzQYbAAIY1qGm3PMWvVVB7h1wujDnVqVlt4R+An4sVEol7HDKGCxJBl3BbmhyHlHjnCZrL7A1Ux5rDB1bboB3H/DuDTDEiveT4Ioq2+mSOTPjZ5o5N3gDkBNiKDHm7Ss4ABqsAk9u+pmiT6CHkq8mAZXC2L4A0NfwlvxZNQJaBZBFr2zfvy4/PWN82pwwd5QnN7lGf3g1vnHUGdE+QHO4545Rd14XT0AaxchQVFhSb02j/m6TtOPd3FgC7+bG+sC7jdg1E28kYkdIV6B60q5S1xs/DbE0k+uMlvqxNdS7Z/ubH5z3nogKeMVv9h8Bp/GgAK4Ojr92ZpLpXrY/Xoi+x4G3dlHin0DYe2IXA6CowskhILUv6H6ZHV2UACv4lgAjzv6rx+zP02ku4hn3IVwP8um+kX3LJPP0Wo4+Nu3J3ne4VjaQ7p24CzrG9i2s20PF3k6FziIVKyUdOU6fCLwdMQy8wdyutbzBXrLf2Tv2nG2c/pbxQGliIrZ5KGppqJQ5WYpKuUaVp02TQ7BVfiSCw3JAjaJ3sM22uDjEfCDiVcUm3+8FcnwmuqtL/t56VfQhDv0dYODU6FZ7X8gynmgGiV42FwPfS+9n79fobnr1NOutDsn1HtbRo8ER60h7Yh2OhLidyfTzp0KBjbwRpdaSKBa3hDOJopwnHjCyIn5u8SHwoE2ety2LtIV36RaF13Xf+8xcSbaoIUgzkvZexoX/xxaMnXoBWIU+MDcYP/eCll7wIuhLHwjDFnm16LMceU8EedakXMQOz+29K3ufrqhEOzf3ITD3dWHHu6LGrO3X8LRSEHpV/FBObMOcG3pXhl5w+ct2zk19CEz9lSgEjsTPb6q8ZtgR+ct2zd4PzqqNQxn8mq1D/rbebQXTpgSOOkDzef0/IeCMmKpe0bDkPwIswD9IP4RhpSh+va+YYDklYRe8YIhe8H9TQL+DljIAAA==',
'app/src/main/res/layout/activity_archive.xml': 'H4sIAOdph2oC/+VaW2/URhR+51dYfi3sJSQhRFkuSSOBBKXKRm3fVrP2ZHca3zoe58JTCEIggQhEVLRV6eWh6kNVKaSJsgQIUn/B+C/wS3rGdja2d9a7SbxLaTdSNp6bZ75z+c45k6nLK6ahLGHqEtuqqOVCSVWwpdk6sRoV1WML5ybUy5fOTN0gFkb0Blq1PabAFMudRJZObaJX1CZjzmSx6GpNbCK3ELUXNNssImexSLFbjNrUw6mO08+0c8hjtqpEPZNG8PbaMtFZs6KaiGnNmoMotljHmCYmjSbrNqiOtMUGtT0LNn9Fp2gZ1Q1cNBGxakddR8NtSmA6YgFCABUjGjJUAKWqUdswviB4+TR7LOlO5xmjvvJRzwIJX+XYFDoY9XBsh7CrcDM3bR1XVAtDg5oW2yn2uEyRU9NsiyUGyYFpdztIF2pUZUjsuDwRP2fUN2+DIpRHJT2zQjjSOdM2Y7ZZUUfEtEtnFPgM+JwNipYIW62oGjRjWus8agKJJjzdhjUCJVGiTz9blGlC9s66q0s3pVVin6l5vMIy1DfznT02hhkgVXWQFjiSUqE8ftTJ4LUVtXrr5me35q4rf+8p/AX/if8e/P5e4U/4L/w3/h3fTM6YsQ2bgsFq4rv4jV5zKDERXU2OqpLbYAAXXSfVzFYNaK/bhq4Wh4dCOAh22SBWoOtjupPGgT/nW/wdb/l3eKvHiUWj7LgjpzuvcOJXPiF6EVGtSZZw1TOTwA4QkNFMQHb5q0ml1AMV02NYl8FSPg+wxE4/VYwbYawdOKfQsO2Ggds0BO4CU4KMQt0Dd2MVbkbP08Fjd+hA70Hj3XBYNwRHR45t6SaxrkUDkrPlZEZggVq4dSmnRet/il2NEif0EmB/W/4df91f4wf8Fd+PqyOxXMxu4IU0XwXtcxIig/1+KfFqkQ9PtYZyh2fHiZ1nnljQesXyDCPsEodKHrLmRngfDfg8+YaoNVKIi/G2aP2UHkX6ktaVYfBMp3WUx3uL2qHYJJ5Zw6bDVqXCzoW/rpuogTPc5Nhohk4nO+XnsGlduvu2ypQTztOlWkoXvrY9asVPxVICPiSM4pBoORTkYfwz2l+clwdxn0IHIxe8CY7g6VnFv++v8wOFvwOf0PIf8Nfi4S0/gPZH/uMTslV5Ikd2ztXcZGT0o/8QiOg1b51VeIvvACWJv/4CFwlgQM8B3/Yf8l2F7x3ROIxU4Put/1B5v/ZM4dsKDNsRwPE3Cn/Dd4Wb5buFExPbSG9ikzuwHJjORJaHjDms2VTPprl8XeFIil4O6XBsvFNq759vKEosjtgCVnukhAGFf1/QXHLGVcOYQY5bUReQ4eL+4s6ajuhidz2Wk5kkeIVhAKWF6RzSiedGWU+xH4mJdy4QbOgFYSXXLcdjQ+SmhLU0g/Pxn0HFBeD74DOEr2gbhb/B30SY2CvTbVg6wHU9uoA0XGsYyHUlE8IEF7ZigHa3+2diAIb5YTx/7DYmmZl2joJjZi8DA2RrVBm1F3HH0epgMMC+dSpwVvsMPyUintUJEw+dpuliEYYGgwZgk0SsO7/qAP5J126iFeFr3ASP9UkJwZBr2ZHYiUzgg4Vspd6hTkLJe9ecYgFZZ1Q01q6C5JbKaAwymVmLwR56JDJZodFonwFPl0whnvDIeHlTePP+vXiMOGUud1RPEmoOMOoUIzOFohsSxGXEGC2aiQVuhS5NDzhkkHjLgtOxPlK3XgL5VcQ7/2aBMIrc5v9IID9AfLoGDNyCwHNrEIKRh5g9y0uCwmOFB3X4XlnINapNzq6AWlTUkW4eRoEAZh+C9RbfFvqdCvRPHsGX3ViMJ+WoNGyzIr8H9WBYHX54l1fpQUZl/V0jBJsaGc+6EBhPUmGvisWFLOO9UMqhYjFSyq5YmEQ7XrWip20FSjJPmDEkJUnIIyVsSV13J0h9Hyn8pX+X7/h3/XVIjiEdeyBy5qCuIDGykxbFS32WGfpEddrWV4cC6oW+MO30Yef7q16I4kS3+oUoTayLyu9ZkSwf+PeAQLZAJE9BOJFg2tWfcAh/CVPWhCRFjidWiWRcyK1qn191PpDjVS1kndNSf67XIElD6sXsgy1sSGl//DC/deXJbcpbHaN83iGkMEKbESwB4+lwHFnCeOSMVPxgKeWEhKjC/kPum8g96ZSUngd4UyrfMuiDI91pZAfP+BP+An7+4N8O/q54qJXosuR+jP8JkegdUVcDh7se1JjXwO73hAMW0SlYPzjgffDJwjdsDLo6P1Q8xqUJZ5ug4LzrQE7il8BIoLPDXwMcwQXGbjBgQzDga0F+7wLyewuk9TgFYdDUhvCxWGUrpD7/nlK1TQtMJL+qfQ7EhlfE/wMJSeSV0Z5CbHHa6u6yJNV8mX4D/uIeejuiOL6tzH81fwpyi/T9+MyWLNvmLD/h3Dzn45LdhNwWg9AvikeyjOo/J0OKXWZT/PELcVMkBMHV5FZwV7kt3KqwvRbfawswnY8dS4CHvvGkEhyE+V0Nw87sQnc5o1RQ7hK6J9qXiEvqxAhSuYZt4W6Bcufz0X+ZwhOxNMPTsRJuAU4R/lFcgm7ASASDNQsyxkYQxYmXpBf8B5glhzjyKwAA',
'app/src/main/res/drawable/premium_showcase_blue.xml': 'H4sIAOdph2oC/3VSQW6DMBC85xXIPRMDgZZGmKhNxQP6AxccsAI2sjdpI/Xx3VAXkpBysZjZ2R3POtt8da13FMZKrRgJlwHxhCp1JVXNyAF2fko2+SJr+UkYv5UWPBQou+aqMlpWjDQA/ZpSWzai43bp8GWpO8r7PTXCUoeRfOHhl0kQXZ7ZhvfCc9R6+GPEiBK4qltB8qw2vJJCwVgzEIyswoRMOuAGtrrVhpGH8CncrtKJLFEtzB8bBVGcRBMrVDUKkzCNCkLRFRi9n2x9ygoajKXqL7o6UVI8xs/xWVRqozDBseJs/GAZiVLUId/z6pznyLdiB8gGl11B97eQkXUzq/vQALpzKPamQ3J4DqlOAY8CjPEo4cQITvgeWpLZ9ZKrEY34HXwDOzt+nM58+0mM2D871Ufe3lsnnIaNI4r8pd2h7N1lmF5Nu1p3/PL4lrwWxd2VBoEj5xlldHrN+eIH5BHjkAIDAAA=',
'app/src/main/res/drawable/premium_showcase_warm.xml': 'H4sIAOdph2oC/3VSW26DMBD8zynQ9puYR2lQhImStjlAb+BiB6yAjexN2kg9fA2hkFf5sZjZ2R3POlt9N7V3FMZKrSiE8wA8oQrNpSopHHDnp7DKZ1nNTsL4tbToOYGyS6a40ZJTqBDbJSG2qETD7HzA54VuCGv3xAhLBgzymee+TKJo8sxWrBXeQC37PwpGFMhUWQvIs9IwLoXCsaYnKMRhApMOmcFXXWtD4SnchOvofSILpxbmj42DKI63EysUH4WLMI02QJwrNHo/2fqSHCsXC28vug6ixUuyTuNOVGijXIJjRWf8YClEqdM5vmW8y3Pka7FDxwaXXVG3t5CRZXVX96kRdTOgrjfpk3Nnn+oU8ChwMR4lniiclT/dcLi7YHI1pBLn0Tfw2befPD8y5Cfdbf/Zqz6y+tFK8dRv3aGOv7Tcl30MOabp5cCrlcfbt8Um3T5eaxAM5H1OGZledD77BX1LfNwGAwAA',
'app/src/main/res/drawable/premium_empty_background.xml': 'H4sIAOdph2oC/3VSW26DMBD8zynQ9jsxj1DRCBOhqjlAb+BiB6yAjexN2kg9fB1iQRJSfixmdnbWs863P10bnISxUisK0SqEQKhKc6lqCkfcLzPYFou8ZWdhlq20GDiBshumuNGSU2gQ+w0htmpEx+zK46tKd4T1B2KEJR6DYhG4L5couiK3DetF4KnN8EfBiAqZqlsBRV4bxqVQONYMBIUkSmHSITP4rlttKLxEcZTG5UQKxUfqLSqTDIjzRaMPk/G35Ni4i/N+0lVelOzW6evHRVRpo1xGY8VltKOlEGdO5/ie8UtiI9+KPTo2vu2Kun+EjKybWd2XRtSdR11vMmTjziG3KcJR4II6STxTcA6/Q0uYXW8d3lo04mr8APtxlmk4m/uK/bM1fWLts4XhedipQx1/O+5Q9ukzzO7c7haapGWalbvk6UrD0JPzjHIyvddi8Qeg+3up5AIAAA=='
}

for rel, payload in FILES.items():
    write_gz64(rel, payload)

archive = ROOT / 'app/src/main/java/com/quietdiary/app/ArchiveActivity.java'
replace_once(archive, '    private LinearLayout entriesContainer;\n', '    private LinearLayout entriesContainer;\n    private LinearLayout emptyState;\n    private TextView emptyTitle;\n    private TextView emptyBody;\n    private MaterialButton emptyAction;\n')
replace_once(archive, '        entriesContainer = findViewById(R.id.archiveEntriesContainer);\n', '        entriesContainer = findViewById(R.id.archiveEntriesContainer);\n        emptyState = findViewById(R.id.archiveEmptyState);\n        emptyTitle = findViewById(R.id.archiveEmptyTitle);\n        emptyBody = findViewById(R.id.archiveEmptyBody);\n        emptyAction = findViewById(R.id.archiveEmptyAction);\n')
replace_once(archive, '''        findViewById(R.id.manualRecordButton).setOnClickListener(v ->\n                startActivity(new Intent(this, ManualRecordActivity.class)\n                        .putExtra(ManualRecordActivity.EXTRA_DREAM, false)));\n''', '''        View.OnClickListener manualRecord = v -> startActivity(new Intent(this, ManualRecordActivity.class)\n                .putExtra(ManualRecordActivity.EXTRA_DREAM, false));\n        findViewById(R.id.manualRecordButton).setOnClickListener(manualRecord);\n        emptyAction.setOnClickListener(manualRecord);\n''')
replace_once(archive, '''        entriesContainer.removeAllViews();\n        if (entries.isEmpty()) {\n            TextView empty = new TextView(this);\n            empty.setText(mode == Mode.TRASH ? "Корзина пуста — удалённые записи будут появляться здесь." : mode == Mode.DREAMS ? "Сны не найдены. Скажите обученную команду сна ночью или запишите сон кнопкой выше." : "Записи не найдены. Нажмите «Записать сейчас» или сохраните новую ночную мысль без рук.");\n            empty.setTextColor(ContextCompat.getColor(this, R.color.qd_muted));\n            empty.setTextSize(15);\n            empty.setPadding(4, dp(20), 4, dp(20));\n            entriesContainer.addView(empty);\n            return;\n        }\n        for (Entry entry : entries) entriesContainer.addView(createCard(entry));\n''', '''        entriesContainer.removeAllViews();\n        boolean empty = entries.isEmpty();\n        emptyState.setVisibility(empty ? View.VISIBLE : View.GONE);\n        entriesContainer.setVisibility(empty ? View.GONE : View.VISIBLE);\n        if (empty) {\n            if (mode == Mode.TRASH) {\n                emptyTitle.setText("Корзина пуста");\n                emptyBody.setText("Удалённые записи будут появляться здесь, пока вы не решите удалить их окончательно.");\n                emptyAction.setVisibility(View.GONE);\n            } else if (mode == Mode.DREAMS) {\n                emptyTitle.setText("Здесь будут ваши сны");\n                emptyBody.setText("Запишите сон утром или сохраните его ночью голосовой командой.");\n                emptyAction.setText("Записать сон");\n                emptyAction.setVisibility(View.VISIBLE);\n            } else {\n                emptyTitle.setText("Здесь будут ваши ночные записи");\n                emptyBody.setText("Мысли, идеи и голосовые заметки, сохранённые ночью, соберутся здесь.");\n                emptyAction.setText("Записать сейчас");\n                emptyAction.setVisibility(View.VISIBLE);\n            }\n            return;\n        }\n        for (Entry entry : entries) entriesContainer.addView(createCard(entry));\n''')
replace_once(archive, '        int text = selected ? android.R.color.white : R.color.qd_primary;\n', '        int text = selected ? R.color.qd_primary_dark : R.color.qd_primary;\n')

night = ROOT / 'app/src/main/java/com/quietdiary/app/NightAssistantActivity.java'
replace_once(night, '            status.setText("Вернитесь на главную и включите его снова, когда будете готовы.");\n', '            status.setText("Включите ночной режим на главной, когда будете готовы.");\n')
replace_once(night, '''            stateTitle.setText("Микрофон готов · жду команду");\n            status.setText(serviceStatusText.isEmpty()\n                    ? "Можно говорить команду. После каждой команды дождитесь сигнала готовности."\n                    : serviceStatusText);\n''', '''            stateTitle.setText("Микрофон готов");\n            status.setText(serviceStatusText.isEmpty()\n                    ? "Жду команду. Говорите спокойно — экран можно выключить."\n                    : serviceStatusText);\n''')

gradle = ROOT / 'app/build.gradle.kts'
replace_once(gradle, '        versionCode = 3001\n        versionName = "0.30.1"\n', '        versionCode = 3002\n        versionName = "0.30.2"\n')

print('Somnori 0.30.2 Premium Pass A applied')
