from pathlib import Path

project=Path('buildsrc/quiet-diary')
voice_tools=project/'app/src/main/java/com/quietdiary/app/SomnoriVoiceTools.java'
test=project/'app/src/test/java/com/quietdiary/app/SomnoriVoiceToolsTest.java'

voice_tools.write_text('''package com.quietdiary.app;\n\n/** Natural low-cognitive-load Russian time phrases for the night voice. */\npublic final class SomnoriVoiceTools {\n    private static final String[] N = {\n            "ноль","один","два","три","четыре","пять","шесть","семь","восемь","девять",\n            "десять","одиннадцать","двенадцать","тринадцать","четырнадцать","пятнадцать",\n            "шестнадцать","семнадцать","восемнадцать","девятнадцать","двадцать"\n    };\n    private SomnoriVoiceTools() {}\n\n    public static String compactTime(int hour, int minute) {\n        int h=((hour%24)+24)%24;\n        int m=((minute%60)+60)%60;\n        String hours=number(h)+" "+plural(h,"час","часа","часов");\n        if (m==0) return hours;\n        return hours+" "+minuteNumber(m)+" "+plural(m,"минута","минуты","минут");\n    }\n\n    private static String minuteNumber(int value) {\n        if (value==1) return "одна";\n        if (value==2) return "две";\n        if (value>20) {\n            int rest=value%10;\n            String head=value<30?"двадцать":value<40?"тридцать":value<50?"сорок":"пятьдесят";\n            if (rest==1) return head+" одна";\n            if (rest==2) return head+" две";\n        }\n        return number(value);\n    }\n\n    static String number(int value) {\n        if (value>=0 && value<=20) return N[value];\n        if (value<60) {\n            int tens=value/10*10;\n            String head=tens==20?"двадцать":tens==30?"тридцать":tens==40?"сорок":"пятьдесят";\n            int rest=value%10;\n            return rest==0?head:head+" "+N[rest];\n        }\n        return String.valueOf(value);\n    }\n\n    private static String plural(int value, String one, String few, String many) {\n        int n=Math.abs(value)%100;\n        if (n>=11 && n<=14) return many;\n        int last=n%10;\n        if (last==1) return one;\n        if (last>=2 && last<=4) return few;\n        return many;\n    }\n}\n''',encoding='utf-8')

test.write_text('''package com.quietdiary.app;\n\nimport static org.junit.Assert.assertEquals;\nimport org.junit.Test;\n\npublic final class SomnoriVoiceToolsTest {\n    @Test public void speaksNaturalFullRussianTime() {\n        assertEquals("три часа двадцать семь минут", SomnoriVoiceTools.compactTime(3,27));\n        assertEquals("тринадцать часов семнадцать минут", SomnoriVoiceTools.compactTime(13,17));\n        assertEquals("восемь часов", SomnoriVoiceTools.compactTime(8,0));\n        assertEquals("один час одна минута", SomnoriVoiceTools.compactTime(1,1));\n        assertEquals("два часа две минуты", SomnoriVoiceTools.compactTime(2,2));\n        assertEquals("двадцать один час двадцать одна минута", SomnoriVoiceTools.compactTime(21,21));\n        assertEquals("двадцать три часа пятьдесят девять минут", SomnoriVoiceTools.compactTime(23,59));\n    }\n}\n''',encoding='utf-8')

print('Somnori natural Russian time phrase applied: 13:17 -> тринадцать часов семнадцать минут')
